# Generated by Django 5.0.1 on 2024-01-19 09:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0003_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=80)),
                ('blog_img', models.ImageField(upload_to='images/')),
                ('blog_description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog_category',
            name='blogcat_description',
            field=models.TextField(max_length=200),
        ),
    ]
