# Generated by Django 5.0.1 on 2024-01-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0006_blog_post_blog_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='blog_des',
            new_name='blog_cat',
        ),
    ]
