# Generated by Django 5.0.1 on 2024-02-01 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0007_rename_blog_des_blog_post_blog_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='blog_cat',
        ),
        migrations.CreateModel(
            name='blog_likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_likes', models.IntegerField(default=0)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBlogs.blog_post')),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='Blog_cat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myBlogs.blog_category'),
        ),
    ]
