# Generated by Django 5.0.1 on 2024-02-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0010_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='c_email',
            new_name='comment_email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='c_id',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='c_name',
            new_name='comment_name',
        ),
    ]
